export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";
export const ADD_GENRE_SUCCESS = "ADD_GENRE_SUCCESS";
export const UPDATE_GENRE_SUCCESS = "UPDATE_GENRE_SUCCESS";
export const DELETE_GENRE_SUCCESS = "DELETE_GENRE_SUCCESS";

export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
